### ISSUE TITLE
Migration between Cosmos databases in different subscriptions/regions

### ISSUE THREAD

**Issue by kavasarala** [AzureCosmosDB/data-migration-desktop-tool#106]
Hi

Can anyone advise if they have used this tool to migrate data from one cosmos db to another cosmos db where both the databases are in different Azure subscriptions. How about different databases in different regions?

Does the tools support this ?  Does this require any specific settings or does the connection string config automatically take care of this?

Regards
Krishna

**Comment by bowencode** [comment]
Because the tool runs locally, there is no direct transfer between Azure resources and so no need to have any specific relationship between data sources. As long as you have access to both (connection strings, firewall rules, etc.) the data will be pulled down over the internet to the machine running the tool and then written back up to the other database.

**Comment by morikat1509** [comment]
@kavasarala I used the tool to migrate data between different Geos, Regions and subscriptions as well. It works fine.
